### ISSUE TITLE
用了 uglyurls = true 参数，文章 标签 分类页，都无法显示了

### ISSUE THREAD

**Issue by 82kg** [dillonzq/LoveIt#266]

**Comment by dillonzq** [comment]
@82kg 哈喽
当 `uglyurls = true` 时的菜单配置:

```toml
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts.html"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags.html"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories.html"
    title = ""
    weight = 3
```
