### ISSUE TITLE
[BUG] toc not shown in prodction

### ISSUE THREAD

**Issue by nirgn975** [dillonzq/LoveIt#297]
### Describe the bug 描述你遇到的错误

The `table-of-content` is shown when in development env, but not in production.
The `toc` set to true on the `post` file, and to `enable` in the `config.toml` file.

### Expected behavior 期待的行为

A `toc` should be displayed on production.

### Build Environment 构建环境

- OS: [macOS]
- Theme version/commit [0.2.3]
- Hugo version [0.69.0]

**Comment by dillonzq** [comment]
Hi, @nirgn975 
Here is a sample of `config.toml`:
![image](https://user-images.githubusercontent.com/30786232/80779134-49a68e80-8b9d-11ea-922b-f4df50d5695b.png)
And remove params about toc in your front matter

**Comment by nirgn975** [comment]
Those are the config params in my `config.toml`, but still when I'm on development mode everything is good, but when I do `hugo server -e production`, every post stretch and the content is missing.
Here is a screenshoot of the horizontal scroll:
![Simple_Twitter_-_Chapter_1__Setup___Stories_of_a_Lifelong_Student_and_Hyper_and_README_md_—___webstormProjects_stories-of-a-lifelong-student](https://user-images.githubusercontent.com/3472902/80790473-9d15de00-8b97-11ea-938d-40700a1d4105.png)

And the `toc` is empty and in the middle of the page:
![Simple_Twitter_-_Chapter_1__Setup___Stories_of_a_Lifelong_Student_and_Hyper](https://user-images.githubusercontent.com/3472902/80790519-bae34300-8b97-11ea-8ff1-4bbd39034f74.png)

**Comment by dillonzq** [comment]
@nirgn975 `public/js/theme.min.js` did not load properly or Javascript in your browser was disabled

**Comment by nirgn975** [comment]
@dillonzq You're right, this happens when I set `lightgallery: true` in a post.
For some reason I got the error:
```
theme.js:320 Uncaught ReferenceError: lightGallery is not defined
```

although I added the lightgallery CDN stuff in `config.toml` file:
```
lightgalleryCSS = 'https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.1.3/css/lightGallery.css'
lightgalleryJS = 'https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.1.3/js/lightGallery.min.js'
lightgalleryThumbnailJS = 'https://cdnjs.cloudflare.com/ajax/libs/lg-thumbnail/1.1.0/lg-thumbnail.min.js'
lightgalleryZoomJS = 'https://cdnjs.cloudflare.com/ajax/libs/lg-zoom/1.1.0/lg-zoom.min.js'
```

**Comment by dillonzq** [comment]
@nirgn975 This theme use native DOM APIs instead of jQuery. All third-party libraries don't need jQuery.

[lightgallery.js](https://github.com/sachinchoolur/lightgallery.js) is an alternative of [lightgallery](https://github.com/sachinchoolur/lightGallery) that does not require jQuery.
Unfortunately, cloudflare does not provide a CDN for this library.
However, you can choose **jsDelivr** instead of **cloudflare**:
```toml
# lightgallery.js@1.1.3
# lg-thumbnail.js@1.1.0 
# lg-zoom.js@1.0.1
lightgalleryCSS = "https://cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/css/lightgallery.min.css"
lightgalleryJS = "https://cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/js/lightgallery.min.js"
lightgalleryThumbnailJS = "https://cdn.jsdelivr.net/npm/lg-thumbnail.js@1.1.0/dist/lg-thumbnail.min.js"
lightgalleryZoomJS = "https://cdn.jsdelivr.net/npm/lg-zoom.js@1.0.1/dist/lg-zoom.min.js"
```
