### ISSUE TITLE
[BUG] Standard Markdown Code Higlighting does not conform to the rendering

### ISSUE THREAD

**Issue by shantanoo-desai** [dillonzq/LoveIt#361]
### Describe the bug 描述你遇到的错误
Code block written back quotes with the type of highlighting renders something very different.
This is observable for all markdown codes with different types (e.g. bash, toml etc.)

within the `posts/my_content.md` file, my content has a `toml` file that I wish to render as code in my write up
E.g.:

    ```toml
     [agent]
       interval = "10s"
       round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      quiet = false
     hostname = ""
     omit_hostname = false 
    ```

e.g:

    ```bash
     mkdir mosquitto/
     mkdir mosquitto/config
     touch mosquitto/config/mosquitto.conf
    ```

Rendered Output:
![image](https://user-images.githubusercontent.com/12070966/82041056-da09c680-96a7-11ea-8233-32913877330e.png)

![image](https://user-images.githubusercontent.com/12070966/82041320-4389d500-96a8-11ea-8041-047bbdb5863f.png)

### Expected behavior 期待的行为

一段简短的对于你期待的行为的描述.

The Page should render the the TOML file, bash  as it is displayed on Hugo LoveIt Example site.

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/12070966/82040804-71bae500-96a7-11ea-8ad5-0ff8dd17b19b.png)

![image](https://user-images.githubusercontent.com/12070966/82041365-569ca500-96a8-11ea-860b-932a1c8914c0.png)

### Build Environment 构建环境

- OS: Windows 10
- Theme version: 0.2.x
 Hugo version:  0.70.0-extended

### Additional Information 补充信息
```toml
baseURL = "https://myURL.com/"
defaultContentLanguage = "en"
languageCode = "en"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  defaultTheme = "dark"
  dateFormat = "02-01-2006"

  [params.app]
    title = "My World"

  [params.search]
    enable = false

  [params.section]
    paginate = 10
    dateFormat = "02-01"

  [params.list]
    paginate = 10
    dateFormat = "02-01"

   [params.home.profile]
     enable = true
     title = "My stuff"
     typeit = true
     social = false
    [params.home.posts]
      paginate = 5

[params.page.code]
  copy = true

[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  Whatsapp = true
  HackerNews = true
  Reddit = true

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "My thoughts and works digitally transcribed"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4
```
Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by dillonzq** [comment]
Hi, @shantanoo-desai

The following configuration is necessary:

```toml
# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
```
