### ISSUE TITLE
[FEATURE] Ability to get rid of Google Fonts

### ISSUE THREAD

**Issue by Selmirrrrr** [dillonzq/LoveIt#387]
### Get rid of Google Fonts

I think that it would be great to provide an easy way to get rid of Google Fonts dependency (i.e. escape tracking).

The only occurrence is in `_variables.scss` :
```less
// ==============================
// Variables
// ==============================

@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@800&display=swap');

```
And the `Nunito` font is only used for the site header: 

```less

// Font style of the header title
--
$header-title-font-family: Nunito, $global-font-family !default;
```

And know that we can override values from `_variables.scss` but this didn't help. By this way we're able to use another font for the header but the `@import` statement remains and lets Google track our users. 

I'm not proficient at all with LESS and Hugo, but would it be any way to provide a parameter to the LESS compiler and have something like this in the `_variables.scss` file: 

```less
// ==============================
// Variables
// ==============================
if ($useGoogleFont) {
  @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@800&display=swap');
  $header-title-font-family: Nunito, $global-font-family !default;
} else {
  $header-title-font-family: $global-font-family !default;
}
```

Thanks for this great theme, it's a pleasure to use and setup thanks to the very complete documentation 👍
