### ISSUE TITLE
[BUG] [TOC] When auto collapse is set true (`auto: true`), the toc endLevel fails to work. 

### ISSUE THREAD

**Issue by SimZhou** [dillonzq/LoveIt#428]
### Describe the bug 描述你遇到的错误

When `auto: false` is set, everything works good.
However, if it is set to be true, the `endLevel` setting in config.toml fails to be vaild. 
To be specific, the toc only shows 2 levels from `startLevel`, no matter what value `endLevel` is. 

### Reproducing the error 复现错误

Firstly, in `config.toml`, set `startLevel` and `endLevel` to show toc from level 1 to level 4:
```toml
[markup]
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 4
```
And I have some bunches of texts like this:
![image](https://user-images.githubusercontent.com/11748629/85248843-a7ac6f80-b484-11ea-82ee-367c96045c13.png) 

If set `auto: false` in article front matter, I have correct TOC output:

![image](https://user-images.githubusercontent.com/11748629/85249012-328d6a00-b485-11ea-8848-21cb7152609f.png)

However if set `auto: true`, I would have only 2 levels available, and some sublevels are not even able to be opened:
![test](https://user-images.githubusercontent.com/11748629/85248952-f954fa00-b484-11ea-9d4b-700c0262a08b.gif)

Then if I set `startLevel` to 2:
```toml
  [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 4
```
Still, I got only 2 levels starting from 2, and some levels not openable:
![test2](https://user-images.githubusercontent.com/11748629/85249732-2acec500-b487-11ea-8a5b-63eaf01600c9.gif)

### Expected behavior 期待的行为

If I set 
```toml
[markup]
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 4
```
All 4 levels from 1st to 4th should be openable. 

### Build Environment 构建环境

- Theme version/commit [e.g. 0.2.10, f787a4e]
- Hugo version v0.72.0/extended

### Preview Environment 预览环境

- OS: Windows 10 x64
- Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

### Additional Information 补充信息

None.
