### ISSUE TITLE
[BUG] Does not show the LinkedIn FontAwesome icon

### ISSUE THREAD

**Issue by Sidra-Kazmi** [dillonzq/LoveIt#504]
### Describe the bug 描述你遇到的错误

LinkedIn FontAwesome icon doesn't show up on the home page social media links.

Where are the FontAwesome icons saved in the LoveIt Template or the ExampleSite of the template.? 

一段简短的对于你遇到的错误的描述.

On the home page, under the Avatar, the LinkedIn FontAwesome icon does not show up.

### Expected behavior 期待的行为
It should should show up just like other social media icons.

一段简短的对于你期待的行为的描述.

### Screenshots 屏幕截图

如果可以的话, 提供屏幕截图对解决问题很有帮助.

![image](https://user-images.githubusercontent.com/69394495/90968470-16706e00-e4b2-11ea-8aa7-0bb23879198e.png)

### Build Environment 构建环境

- OS: [e.g. Windows 10, macOS, Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [e.g. 0.69.0]

v0.74.3/extended

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
- Browser [e.g. Chrome, Safari, Firefox]

Windows 10

Chrome, Opera, Edge.

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...
` C:\Hugo\loveit\assets\data\social.yml `

```
# 001: Github
github:
  Weight: 1
  Prefix: https://github.com/
  Title: GitHub
  Icon:
    Class: fab fa-github-alt fa-fw
    #Class: fab fa-github fa-fw

# 002: LinkedIn
linkedin:
  Weight: 2
  Prefix: https://linkedin.com/in/
  Title: LinkedIn
  Icon:
    Class: fab fa-linkedin fa-fw
```
