### ISSUE TITLE
[QUESTION] How to control wordCount,readingTime...

### ISSUE THREAD

**Issue by cityiron** [dillonzq/LoveIt#532]
### Describe the bug 描述你遇到的错误

I not found how to control the wordCount, readTime...

### Screenshots 屏幕截图

I want it look like:
![image](https://user-images.githubusercontent.com/55343460/95536568-e52a0e00-0a1d-11eb-86f6-88a51dd9eb56.png)

I run a test project like:
![image](https://user-images.githubusercontent.com/55343460/95536602-f5da8400-0a1d-11eb-891d-f4fbcb15d07e.png)

the config is:
```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
# theme
# 主题
theme = "LoveIt"

[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.2.X"
```
but when I run in my blog project, even I use same config:
```toml
baseURL = "https://blog.funnycode.cn/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写 en-us
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Funnycode"
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "loveIt"

[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.2.X"
```

the page is:
![image](https://user-images.githubusercontent.com/55343460/95536743-4eaa1c80-0a1e-11eb-9760-196ca2052bf9.png)

only time in here.

### Build Environment 构建环境

- OS: [macOS]
- Theme version/commit [0.2.0]
- Hugo version [Hugo Static Site Generator v0.76.0/extended darwin/amd64 BuildDate: unknown]
