### ISSUE TITLE
[FEATURE] 网页导入js文件的问题

### ISSUE THREAD

**Issue by dyhgo** [dillonzq/LoveIt#638]
请问一下如何在每个网页导入指定的js文件（用script标签），有什么接口可以自动导入吗，不涉及到修改html代码？

**Comment by wang95** [comment]
https://hugoloveit.com/zh-cn/theme-documentation-extended-shortcodes/#11-script

**Comment by eyllanesc** [comment]
@dyhgo Also see https://github.com/dillonzq/LoveIt/blob/f787a4e5ad4edf60467658d10c286248dc5027a6/exampleSite/config.toml#L934-L938

**Comment by dyhgo** [comment]
@eyllanesc thank you, then how to import two or more javascript files in this way?

**Comment by eyllanesc** [comment]
@dyhgo Use 

```toml
 [params.page.library.js] 
   js1 = "some.js" 
   js2 = "https://cdn.example.com/some.js" 
```
