### ISSUE TITLE
[BUG] Comment section won't show up

### ISSUE THREAD

**Issue by VincentLeV** [dillonzq/LoveIt#657]
### Describe the bug 描述你遇到的错误
I've tried to enable the comment section using Commento but it didn't work. I then tried also all of the other supported tech like Utterances etc. and still didn't work

### Expected behavior 期待的行为
Expect to show the comment section for each post

### Build Environment 构建环境

- OS: Windows 10
- Theme version/commit: I downloaded version [v0.2.10](https://github.com/dillonzq/LoveIt/releases/tag/v0.2.10) and inside config.toml, I added `version = "0.2.X"`
- Hugo version: v0.89.4

### Preview Environment 预览环境

- OS: Windows 10
- Browser: Brave, tested also on Microsoft Edge and still the same

### Additional Information 补充信息
- config.toml

```
[params]
  version = "0.2.X"
  ...
    [params.page.comment]
        enable = true
        [params.page.comment.commento]
          enable = true
```

- Inside post
```
---
...
comment: 
  enable: true
---
```
I also tried this, didn't work
```
---
...
comment: 
  enable: true
  commento:
    enable: true
---
```

- Github Actions

```
- name: Setup Hugo
    uses: peaceiris/actions-hugo@v2
    with:
      hugo-version: 'latest'
      extended: true
- name: Build
    run: hugo --minify
```
