### ISSUE TITLE
[BUG] HTML在Markdown中無顯示

### ISSUE THREAD

**Issue by nataliepjlin** [dillonzq/LoveIt#701]
### Describe the bug 描述你遇到的错误
HTML在Markdown中無顯示，如圖
![image](https://user-images.githubusercontent.com/100992247/175809250-0dd58cdc-6368-456e-a822-361a56145a31.png)
該篇文章MD檔如下
```
---
title: "Test"
subtitle: ""
date: 2022-06-26T17:59:44+08:00
lastmod: 2022-06-26T17:59:44+08:00
draft: false
author: ""
authorLink: ""
description: ""
license: ""
images: []

tags: []
categories: []

featuredImage: ""
featuredImagePreview: ""

hiddenFromHomePage: false
hiddenFromSearch: false
twemoji: false
lightgallery: true
ruby: true
fraction: true
fontawesome: true
linkToMarkdown: true
rssFullText: false

toc:
  enable: true
  auto: true
code:
  copy: true
  maxShownLines: 50
math:
  enable: false
  # ...
mapbox:
  # ...
share:
  enable: true
  # ...
comment:
  enable: true
  # ...
library:
  css:
    # someCSS = "some.css"
    # located in "assets/"
    # Or
    # someCSS = "https://cdn.example.com/some.css"
  js:
    # someJS = "some.js"
    # located in "assets/"
    # Or
    # someJS = "https://cdn.example.com/some.js"
seo:
  images: []
  # ...
---
<p>
  In this example, <code>&lt;section&gt;&lt;/section&gt;</code> should be wrapped with <strong>code</strong>.
</p>
```
