### ISSUE TITLE
[BUG] Huge spacing around image

### ISSUE THREAD

**Issue by SingularisArt** [dillonzq/LoveIt#713]
### Describe the bug 描述你遇到的错误

When adding an image, I get huge spacing around the image.

### Screenshots 屏幕截图

![Screenshot from 2022-07-12 18-05-55](https://user-images.githubusercontent.com/57925294/178626449-f868d74f-5a70-49f0-851c-7f92eef953b1.png)

### Build Environment 构建环境

- OS: 5.15.50-1 MANJARO
- Theme version/commit: a0d614432860f909e79cd7447978986e0ab556c3
- Hugo version: hugo v0.101.0+extended linux/amd64 BuildDate=unknown

### Preview Environment 预览环境

- OS: 5.15.50-1 MANJARO
- Browser type and version: Google Chrome 103.0.5060.114

#### Frontmatter

```yaml
---
weight: 1
title: 'Note Taking with LaTeX: Part I (NeoVim)'
subtitle: 'LaTeX Note-Taking'
date: 2022-01-01
lastmod: 2022-01-01
draft: false
author: 'Hashem A. Damrah'
authorLink: 'https://github.com/SingularisArt'
description: 'I go over using NeoVim and LaTeX to take notes with, but I specifically talk about talking notes with Mathematics.'
images: []

tags: ['tutorial', 'notes', 'note taking']
categories: ['latex', 'school']

lightgallery: true

toc:
  auto: true
math:
  enable: true
---
```
