### ISSUE TITLE
[BUG] Algolia search results cannot be eliminated on mobile.

### ISSUE THREAD

**Issue by Charles94jp** [dillonzq/LoveIt#760]
### Describe the bug 描述你遇到的错误

Searching on the mobile side, if I don't click to jump, I can't eliminate the search results.

移动端进行搜索，如果不点击跳转，无论是滑动内容、重新点击右上角图标，都无法消除搜索结果。

### Build Environment 构建环境

- OS:  
        Windows 11
- Theme version/commit 
  v0.2.11,[e9e89a4](https://github.com/dillonzq/LoveIt/tree/e9e89a4613baee823596822b7d246f5931263491)
- Hugo version  
  v0.104.3

### Preview Environment 预览环境

- OS: 
  iPhone 
- Browser type/version
  Safari

### Additional Information 补充信息

my config

```toml
  # LoveIt 新增 | 0.2.0 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    # lunr无法使用貌似
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # LoveIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # LoveIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = "xxx"
      appID = "xxx"
      searchKey = "xxx"
```
