### ISSUE TITLE
[FEATURE] Table of Contents (TOC) Scrollbar

### ISSUE THREAD

**Issue by jamesdeluk** [dillonzq/LoveIt#783]
If there is a long page with a long TOC, the TOC overflows and cannot be seen. The only way to see the rest of the TOC is to scroll to the bottom of the page.

Ex: https://www.jamesgibbins.com/posts/consumption-week1/

Can the TOC have a separate scroll feature?

**Comment by jamesdeluk** [comment]
This can be _kinda_ fixed with `_custom.scss`:
```css
#TableOfContents {
  overflow-y: scroll;
  max-height: 500px;
}
```
Of course this does impose a max height, making it bad on large screens etc, but it seems okay on my 1920x1080.
