### ISSUE TITLE
[FEATURE] Social icon title translation

### ISSUE THREAD

**Issue by airsiena** [dillonzq/LoveIt#788]
I would like it to be possible to translate the `Title` value of some social icons inside *assets/data/social.yml*.

Specifically I am referring to the `Phone` icon and its `Title` that I would like to be able to translate into other languages and also other custom icons that I have added to my site, for which I would like to translate the corresponding `Title:` value.

For example, I added an icon in *assets/data/social.yml* for the address and I would like to be able to use some kind of code like this:

```
# Address
address:
  Weight: 200
  Template: https://maps.apple.com/?q=%v
  Title: {{ i18n "address" }}
  Icon:
    Class: fas fa-building fa-fw
```
